### ISSUE TITLE
org.gnome.desktop.background depends on color-sheme in Ubuntu 22.04 +

### ISSUE THREAD

**Issue by bukowa** [crackcomm/vim-ate-my-file#2]
See https://askubuntu.com/a/69500
https://github.com/crackcomm/vim-ate-my-file/blob/a347355d27d23bef6770d8a7390dbc57b75675bb/apod-bg.sh#L8

Zrobie potem PR :D

**Comment by crackcomm** [comment]
Fixed in #3. Thanks.
